// This is an autogenerated file from Firebase Studio.
"use client";

import { usePathname } from 'next/navigation';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import type { Profile } from '@/lib/types';

export default function AppContent({ children, profile }: { children: React.ReactNode, profile: Profile }) {
    const pathname = usePathname();
    const isAdminPage = pathname.startsWith('/admin');

    if (isAdminPage) {
        return <>{children}</>;
    }

    return (
        <div className="flex flex-col min-h-screen">
            <Header profile={profile} />
            <main className="flex-grow container mx-auto px-4 py-8">
                {children}
            </main>
            <Footer profile={profile} />
        </div>
    );
}
